[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "kittyai"
version = "1.0.0"
description = "AI integration for Kitty terminal"
dependencies = [
    "openai",
    "python-dotenv",
]

[project.scripts]
kittyai = "app:main"
